// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#include "NativeCsOnlyListener.hpp"  // my header

namespace djinni_generated {

NativeCsOnlyListener::NativeCsOnlyListener() : ::djinni::JniInterface<::testsuite::CsOnlyListener, NativeCsOnlyListener>() {}

NativeCsOnlyListener::~NativeCsOnlyListener() = default;


}  // namespace djinni_generated
