// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#pragma once

#include "cs_only_listener.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCsOnlyListener final : ::djinni::JniInterface<::testsuite::CsOnlyListener, NativeCsOnlyListener> {
public:
    using CppType = std::shared_ptr<::testsuite::CsOnlyListener>;
    using CppOptType = std::shared_ptr<::testsuite::CsOnlyListener>;
    using JniType = jobject;

    using Boxed = NativeCsOnlyListener;

    ~NativeCsOnlyListener();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeCsOnlyListener>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeCsOnlyListener>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeCsOnlyListener();
    friend ::djinni::JniClass<NativeCsOnlyListener>;
    friend ::djinni::JniInterface<::testsuite::CsOnlyListener, NativeCsOnlyListener>;

};

}  // namespace djinni_generated
