// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

#pragma once

namespace Djinni { namespace TestSuite {

[System::Flags]
public enum class AccessFlags {
    Nobody = 0,
    OwnerRead = 1 << 0,
    OwnerWrite = 1 << 1,
    OwnerExecute = 1 << 2,
    GroupRead = 1 << 3,
    GroupWrite = 1 << 4,
    GroupExecute = 1 << 5,
    SystemRead = 1 << 6,
    SystemWrite = 1 << 7,
    SystemExecute = 1 << 8,
    Everybody = 0 | OwnerRead | OwnerWrite | OwnerExecute | GroupRead | GroupWrite | GroupExecute | SystemRead | SystemWrite | SystemExecute,
};

} }  // namespace Djinni::TestSuite
