// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from primtypes.djinni

#pragma once

#include "assorted_primitives.hpp"

namespace Djinni { namespace TestSuite {

public ref class AssortedPrimitives : System::IEquatable<AssortedPrimitives^> {
public:

    property bool B
    {
        bool get();
    }

    property char Eight
    {
        char get();
    }

    property short Sixteen
    {
        short get();
    }

    property int Thirtytwo
    {
        int get();
    }

    property __int64 Sixtyfour
    {
        __int64 get();
    }

    property float Fthirtytwo
    {
        float get();
    }

    property double Fsixtyfour
    {
        double get();
    }

    property System::Nullable<bool> OB
    {
        System::Nullable<bool> get();
    }

    property System::Nullable<char> OEight
    {
        System::Nullable<char> get();
    }

    property System::Nullable<short> OSixteen
    {
        System::Nullable<short> get();
    }

    property System::Nullable<int> OThirtytwo
    {
        System::Nullable<int> get();
    }

    property System::Nullable<__int64> OSixtyfour
    {
        System::Nullable<__int64> get();
    }

    property System::Nullable<float> OFthirtytwo
    {
        System::Nullable<float> get();
    }

    property System::Nullable<double> OFsixtyfour
    {
        System::Nullable<double> get();
    }

    AssortedPrimitives(bool b,
                       char eight,
                       short sixteen,
                       int thirtytwo,
                       __int64 sixtyfour,
                       float fthirtytwo,
                       double fsixtyfour,
                       System::Nullable<bool> oB,
                       System::Nullable<char> oEight,
                       System::Nullable<short> oSixteen,
                       System::Nullable<int> oThirtytwo,
                       System::Nullable<__int64> oSixtyfour,
                       System::Nullable<float> oFthirtytwo,
                       System::Nullable<double> oFsixtyfour);

    System::String^ ToString() override;

    virtual bool Equals(AssortedPrimitives^ other);
    bool Equals(System::Object^ obj) override;
    int GetHashCode() override;

internal:
    using CppType = ::testsuite::AssortedPrimitives;
    using CsType = AssortedPrimitives;

    static CppType ToCpp(CsType^ cs);
    static CsType^ FromCpp(const CppType& cpp);

private:
    bool _b;
    char _eight;
    short _sixteen;
    int _thirtytwo;
    __int64 _sixtyfour;
    float _fthirtytwo;
    double _fsixtyfour;
    System::Nullable<bool> _oB;
    System::Nullable<char> _oEight;
    System::Nullable<short> _oSixteen;
    System::Nullable<int> _oThirtytwo;
    System::Nullable<__int64> _oSixtyfour;
    System::Nullable<float> _oFthirtytwo;
    System::Nullable<double> _oFsixtyfour;
};

} }  // namespace Djinni::TestSuite
