// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#pragma once

#include "CsClientReturnedRecord.hpp"
#include "client_interface.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

public ref class ClientInterface abstract {
public:
    virtual ClientReturnedRecord^ GetRecord(__int64 recordId, System::String^ utf8string, System::String^ misc) abstract;

    virtual double IdentifierCheck(array<System::Byte>^ data, int r, __int64 jret) abstract;

    virtual System::String^ ReturnStr() abstract;

    virtual System::String^ MethTakingInterface(ClientInterface^ i) abstract;

    virtual System::String^ MethTakingOptionalInterface(ClientInterface^ i) abstract;

internal:
    using CppType = std::shared_ptr<::testsuite::ClientInterface>;
    using CppOptType = std::shared_ptr<::testsuite::ClientInterface>;
    using CsType = ClientInterface^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};

} }  // namespace Djinni::TestSuite
