// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#pragma once

#include "client_returned_record.hpp"

namespace Djinni { namespace TestSuite {

/** Record returned by a client */
public ref class ClientReturnedRecord {
public:

    property __int64 RecordId
    {
        __int64 get();
    }

    property System::String^ Content
    {
        System::String^ get();
    }

    property System::String^ Misc
    {
        System::String^ get();
    }

    ClientReturnedRecord(__int64 recordId,
                         System::String^ content,
                         System::String^ misc);

    System::String^ ToString() override;

internal:
    using CppType = ::testsuite::ClientReturnedRecord;
    using CsType = ClientReturnedRecord;

    static CppType ToCpp(CsType^ cs);
    static CsType^ FromCpp(const CppType& cpp);

private:
    __int64 _recordId;
    System::String^ _content;
    System::String^ _misc;
};

} }  // namespace Djinni::TestSuite
