// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#pragma once

#include "CsConstantRecord.hpp"
#include "constants.hpp"

namespace Djinni { namespace TestSuite {

/** Record containing constants */
public ref class Constants {
public:

    /** bool_constant has documentation. */
    literal bool BoolConstant = true;

    literal char I8Constant = 1;

    literal short I16Constant = 2;

    literal int I32Constant = 3;

    literal __int64 I64Constant = 4;

    literal float F32Constant = 5.0F;

    /**
     * f64_constant has long documentation.
     * (Second line of multi-line documentation.
     *   Indented third line of multi-line documentation.)
     */
    literal double F64Constant = 5.0;

    static initonly System::Nullable<bool> OptBoolConstant;

    static initonly System::Nullable<char> OptI8Constant;

    /** opt_i16_constant has documentation. */
    static initonly System::Nullable<short> OptI16Constant;

    static initonly System::Nullable<int> OptI32Constant;

    static initonly System::Nullable<__int64> OptI64Constant;

    /**
     * opt_f32_constant has long documentation.
     * (Second line of multi-line documentation.
     *   Indented third line of multi-line documentation.)
     */
    static initonly System::Nullable<float> OptF32Constant;

    static initonly System::Nullable<double> OptF64Constant;

    static initonly System::String^ StringConstant;

    static initonly System::String^ OptStringConstant;

    static initonly ConstantRecord^ ObjectConstant;

    /**
     * No support for null optional constants
     * No support for optional constant records
     * No support for constant binary, list, set, map
     */
    literal bool Dummy = false;

    static Constants() {
        OptBoolConstant = System::Nullable<bool>(true);
        OptI8Constant = System::Nullable<char>(1);
        OptI16Constant = System::Nullable<short>(2);
        OptI32Constant = System::Nullable<int>(3);
        OptI64Constant = System::Nullable<__int64>(4);
        OptF32Constant = System::Nullable<float>(5.0);
        OptF64Constant = System::Nullable<double>(5.0);
        StringConstant = "string-constant";
        OptStringConstant = "string-constant";
        ObjectConstant = gcnew ConstantRecord(
            I32Constant /* _someInteger */ ,
            StringConstant /* _someString */ );
    }

    System::String^ ToString() override;

internal:
    using CppType = ::testsuite::Constants;
    using CsType = Constants;

    static CppType ToCpp(CsType^ cs);
    static CsType^ FromCpp(const CppType& cpp);

private:
};

} }  // namespace Djinni::TestSuite
