// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#pragma once

#include "Conflict.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

public ref class Conflict abstract {
public:

internal:
    using CppType = std::shared_ptr<::testsuite::Conflict>;
    using CppOptType = std::shared_ptr<::testsuite::Conflict>;
    using CsType = Conflict^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};

} }  // namespace Djinni::TestSuite
