// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#include "CsConstantsInterface.hpp"  // my header
#include "Error.hpp"
#include "Marshal.hpp"
#include "WrapperCache.hpp"

namespace Djinni { namespace TestSuite {

ref class ConstantsInterfaceCppProxy : public ConstantsInterface {
    using CppType = std::shared_ptr<::testsuite::ConstantsInterface>;
    using HandleType = ::djinni::CppProxyCache::Handle<CppType>;
public:
    ConstantsInterfaceCppProxy(const CppType& cppRef) : _cppRefHandle(new HandleType(cppRef)) {}

    void Dummy() override {
        try {
            _cppRefHandle->get()->dummy();
        } DJINNI_TRANSLATE_EXCEPTIONS()
    }

    CppType djinni_private_get_proxied_cpp_object() {
        return _cppRefHandle->get();
    }

private:
    AutoPtr<HandleType> _cppRefHandle;
};

ConstantsInterface::CppType ConstantsInterface::ToCpp(ConstantsInterface::CsType cs)
{
    if (!cs) {
        return nullptr;
    }
    return dynamic_cast<ConstantsInterfaceCppProxy^>(cs)->djinni_private_get_proxied_cpp_object();
}

ConstantsInterface::CsType ConstantsInterface::FromCppOpt(const ConstantsInterface::CppOptType& cpp)
{
    if (!cpp) {
        return nullptr;
    }
    return ::djinni::get_cpp_proxy<ConstantsInterfaceCppProxy^>(cpp);
}

} }  // namespace Djinni::TestSuite
