// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#include "CsConstantRecord.hpp"  // my header
#include "Marshal.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

ConstantRecord::ConstantRecord(int someInteger,
                               System::String^ someString)
: _someInteger(someInteger)
, _someString(someString)
{}

int ConstantRecord::SomeInteger::get()
{
    return _someInteger;
}

System::String^ ConstantRecord::SomeString::get()
{
    return _someString;
}

System::String^ ConstantRecord::ToString()
{
    return "ConstantRecord[TODO]"; // TODO
}

ConstantRecord::CppType ConstantRecord::ToCpp(ConstantRecord::CsType^ cs)
{
    ASSERT(cs != nullptr);
    return {::djinni::I32::ToCpp(cs->SomeInteger),
            ::djinni::String::ToCpp(cs->SomeString)};
}

ConstantRecord::CsType^ ConstantRecord::FromCpp(const ConstantRecord::CppType& cpp)
{
    return gcnew ConstantRecord::CsType(::djinni::I32::FromCpp(cpp.some_integer),
                                        ::djinni::String::FromCpp(cpp.some_string));
}

} }  // namespace Djinni::TestSuite
