// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#pragma once

#include "CsConflict.hpp"
#include "conflict_user.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

public ref class ConflictUser abstract {
public:
    virtual Conflict^ Conflict() abstract;

    virtual bool ConflictArg(System::Collections::Generic::HashSet<::Djinni::TestSuite::Conflict^>^ cs) abstract;

internal:
    using CppType = std::shared_ptr<::testsuite::ConflictUser>;
    using CppOptType = std::shared_ptr<::testsuite::ConflictUser>;
    using CsType = ConflictUser^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};

} }  // namespace Djinni::TestSuite
