// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#pragma once

#include "constant_record.hpp"

namespace Djinni { namespace TestSuite {

/** Record for use in constants */
public ref class ConstantRecord {
public:

    property int SomeInteger
    {
        int get();
    }

    property System::String^ SomeString
    {
        System::String^ get();
    }

    ConstantRecord(int someInteger,
                   System::String^ someString);

    System::String^ ToString() override;

internal:
    using CppType = ::testsuite::ConstantRecord;
    using CsType = ConstantRecord;

    static CppType ToCpp(CsType^ cs);
    static CsType^ FromCpp(const CppType& cpp);

private:
    int _someInteger;
    System::String^ _someString;
};

} }  // namespace Djinni::TestSuite
