// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#pragma once

#include "constants_interface.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

public ref class ConstantsInterface abstract {
public:
    virtual void Dummy() abstract;

internal:
    using CppType = std::shared_ptr<::testsuite::ConstantsInterface>;
    using CppOptType = std::shared_ptr<::testsuite::ConstantsInterface>;
    using CsType = ConstantsInterface^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};

} }  // namespace Djinni::TestSuite
