// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#include "CsConstants.hpp"  // my header
#include "Marshal.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {


System::String^ Constants::ToString()
{
    return "Constants[TODO]"; // TODO
}

Constants::CppType Constants::ToCpp(Constants::CsType^ cs)
{
    ASSERT(cs != nullptr);
    return {};
}

Constants::CsType^ Constants::FromCpp(const Constants::CppType& cpp)
{
    return gcnew Constants::CsType();
}

} }  // namespace Djinni::TestSuite
