// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from exception.djinni

#pragma once

#include "cpp_exception.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

public ref class CppException abstract {
public:
    virtual int ThrowAnException() abstract;

    static CppException^ Get();

internal:
    using CppType = std::shared_ptr<::testsuite::CppException>;
    using CppOptType = std::shared_ptr<::testsuite::CppException>;
    using CsType = CppException^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};

} }  // namespace Djinni::TestSuite
