// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from exception.djinni

#include "CsCppException.hpp"  // my header
#include "Error.hpp"
#include "Marshal.hpp"
#include "WrapperCache.hpp"

namespace Djinni { namespace TestSuite {

CppException^ CppException::Get() {
    try {
        auto cs_result = ::testsuite::CppException::get();
        return ::Djinni::TestSuite::CppException::FromCpp(cs_result);
    } DJINNI_TRANSLATE_EXCEPTIONS()
    return nullptr; // Unreachable! (Silencing compiler warnings.)
}

ref class CppExceptionCppProxy : public CppException {
    using CppType = std::shared_ptr<::testsuite::CppException>;
    using HandleType = ::djinni::CppProxyCache::Handle<CppType>;
public:
    CppExceptionCppProxy(const CppType& cppRef) : _cppRefHandle(new HandleType(cppRef)) {}

    int ThrowAnException() override {
        try {
            auto cs_result = _cppRefHandle->get()->throw_an_exception();
            return ::djinni::I32::FromCpp(cs_result);
        } DJINNI_TRANSLATE_EXCEPTIONS()
        return 0; // Unreachable! (Silencing compiler warnings.)
    }

    CppType djinni_private_get_proxied_cpp_object() {
        return _cppRefHandle->get();
    }

private:
    AutoPtr<HandleType> _cppRefHandle;
};

CppException::CppType CppException::ToCpp(CppException::CsType cs)
{
    if (!cs) {
        return nullptr;
    }
    return dynamic_cast<CppExceptionCppProxy^>(cs)->djinni_private_get_proxied_cpp_object();
}

CppException::CsType CppException::FromCppOpt(const CppException::CppOptType& cpp)
{
    if (!cpp) {
        return nullptr;
    }
    return ::djinni::get_cpp_proxy<CppExceptionCppProxy^>(cpp);
}

} }  // namespace Djinni::TestSuite
