// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#pragma once

#include "cs_only_listener.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

public ref class CsOnlyListener abstract {
public:

internal:
    using CppType = std::shared_ptr<::testsuite::CsOnlyListener>;
    using CppOptType = std::shared_ptr<::testsuite::CsOnlyListener>;
    using CsType = CsOnlyListener^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};

} }  // namespace Djinni::TestSuite
