// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from date.djinni

#include "CsDateRecord.hpp"  // my header
#include "Marshal.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

DateRecord::DateRecord(System::DateTime createdAt)
: _createdAt(createdAt)
{}

System::DateTime DateRecord::CreatedAt::get()
{
    return _createdAt;
}

System::String^ DateRecord::ToString()
{
    return "DateRecord[TODO]"; // TODO
}

bool DateRecord::Equals(DateRecord^ other) {
    if (ReferenceEquals(nullptr, other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return CreatedAt.Equals(other->CreatedAt);
}

bool DateRecord::Equals(System::Object^ obj) {
    if (ReferenceEquals(nullptr, obj)) return false;
    if (ReferenceEquals(this, obj)) return true;
    return obj->GetType() == GetType() && Equals((DateRecord^) obj);
}

int DateRecord::GetHashCode() {
    auto hashCode = CreatedAt.GetHashCode();
    return hashCode;
}

int DateRecord::CompareTo(DateRecord^ other) {
    if (ReferenceEquals(this, other)) return 0;
    if (ReferenceEquals(nullptr, other)) return 1;
    return CreatedAt.CompareTo(other->CreatedAt);
}

DateRecord::CppType DateRecord::ToCpp(DateRecord::CsType^ cs)
{
    ASSERT(cs != nullptr);
    return {::djinni::Date::ToCpp(cs->CreatedAt)};
}

DateRecord::CsType^ DateRecord::FromCpp(const DateRecord::CppType& cpp)
{
    return gcnew DateRecord::CsType(::djinni::Date::FromCpp(cpp.created_at));
}

} }  // namespace Djinni::TestSuite
