// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from date.djinni

#pragma once

#include "Marshal.hpp"
#include "date_record.hpp"

namespace Djinni { namespace TestSuite {

public ref class DateRecord : System::IComparable<DateRecord^>, System::IEquatable<DateRecord^> {
public:

    property System::DateTime CreatedAt
    {
        System::DateTime get();
    }

    DateRecord(System::DateTime createdAt);

    System::String^ ToString() override;

    virtual bool Equals(DateRecord^ other);
    bool Equals(System::Object^ obj) override;
    int GetHashCode() override;

    virtual int CompareTo(DateRecord^ other);
internal:
    using CppType = ::testsuite::DateRecord;
    using CsType = DateRecord;

    static CppType ToCpp(CsType^ cs);
    static CsType^ FromCpp(const CppType& cpp);

private:
    System::DateTime _createdAt;
};

} }  // namespace Djinni::TestSuite
