// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

#pragma once

namespace Djinni { namespace TestSuite {

[System::Flags]
public enum class EmptyFlags {
    None = 0,
    All = 0,
};

} }  // namespace Djinni::TestSuite
