// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#include "CsEmptyRecord.hpp"  // my header
#include "Marshal.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {


System::String^ EmptyRecord::ToString()
{
    return "EmptyRecord[TODO]"; // TODO
}

EmptyRecord::CppType EmptyRecord::ToCpp(EmptyRecord::CsType^ cs)
{
    ASSERT(cs != nullptr);
    return {};
}

EmptyRecord::CsType^ EmptyRecord::FromCpp(const EmptyRecord::CppType& cpp)
{
    return gcnew EmptyRecord::CsType();
}

} }  // namespace Djinni::TestSuite
