// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

#include "CsEmptyFlags.hpp"  // my header

namespace Djinni { namespace TestSuite {

// Empty... making sure the symbols get included in the build.

} }  // namespace Djinni::TestSuite
