// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

#pragma once

#include "CsColor.hpp"
#include "enum_usage_interface.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

public ref class EnumUsageInterface abstract {
public:
    virtual Color E(Color e) abstract;

    virtual System::Nullable<Color> O(System::Nullable<Color> o) abstract;

    virtual System::Collections::Generic::List<Color>^ L(System::Collections::Generic::List<Color>^ l) abstract;

    virtual System::Collections::Generic::HashSet<Color>^ S(System::Collections::Generic::HashSet<Color>^ s) abstract;

    virtual System::Collections::Generic::Dictionary<Color, Color>^ M(System::Collections::Generic::Dictionary<Color, Color>^ m) abstract;

internal:
    using CppType = std::shared_ptr<::testsuite::EnumUsageInterface>;
    using CppOptType = std::shared_ptr<::testsuite::EnumUsageInterface>;
    using CsType = EnumUsageInterface^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};

} }  // namespace Djinni::TestSuite
