// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

#pragma once

#include "CsColor.hpp"
#include "enum_usage_record.hpp"

namespace Djinni { namespace TestSuite {

public ref class EnumUsageRecord {
public:

    property Color E
    {
        Color get();
    }

    property System::Nullable<Color> O
    {
        System::Nullable<Color> get();
    }

    property System::Collections::Generic::List<Color>^ L
    {
        System::Collections::Generic::List<Color>^ get();
    }

    property System::Collections::Generic::HashSet<Color>^ S
    {
        System::Collections::Generic::HashSet<Color>^ get();
    }

    property System::Collections::Generic::Dictionary<Color, Color>^ M
    {
        System::Collections::Generic::Dictionary<Color, Color>^ get();
    }

    EnumUsageRecord(Color e,
                    System::Nullable<Color> o,
                    System::Collections::Generic::List<Color>^ l,
                    System::Collections::Generic::HashSet<Color>^ s,
                    System::Collections::Generic::Dictionary<Color, Color>^ m);

    System::String^ ToString() override;

internal:
    using CppType = ::testsuite::EnumUsageRecord;
    using CsType = EnumUsageRecord;

    static CppType ToCpp(CsType^ cs);
    static CsType^ FromCpp(const CppType& cpp);

private:
    Color _e;
    System::Nullable<Color> _o;
    System::Collections::Generic::List<Color>^ _l;
    System::Collections::Generic::HashSet<Color>^ _s;
    System::Collections::Generic::Dictionary<Color, Color>^ _m;
};

} }  // namespace Djinni::TestSuite
