// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

#include "CsExternInterface2.hpp"  // my header
#include "Error.hpp"
#include "Marshal.hpp"
#include "WrapperCache.hpp"

namespace Djinni { namespace TestSuite {

ExternInterface2::CppType ExternInterface2::ToCpp(ExternInterface2::CsType cs)
{
    if (!cs) {
        return nullptr;
    }
    DJINNI_UNIMPLEMENTED("Interface not implementable in any language.");
}

ExternInterface2::CsType ExternInterface2::FromCppOpt(const ExternInterface2::CppOptType& cpp)
{
    if (!cpp) {
        return nullptr;
    }
    DJINNI_UNIMPLEMENTED("Interface not implementable in any language.");
}

} }  // namespace Djinni::TestSuite
