// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from extended_record.djinni

#pragma once

#include "extended_record.hpp"

namespace Djinni { namespace TestSuite {

/** Extended record */
public ref class ExtendedRecord {
public:

    static initonly ExtendedRecord^ ExtendedRecordConst;

    static ExtendedRecord() {
        ExtendedRecordConst = gcnew ExtendedRecord(
            true /* _foo */ );
    }

    property bool Foo
    {
        bool get();
    }

    ExtendedRecord(bool foo);

    System::String^ ToString() override;

internal:
    using CppType = ::testsuite::ExtendedRecord;
    using CsType = ExtendedRecord;

    static CppType ToCpp(CsType^ cs);
    static CsType^ FromCpp(const CppType& cpp);

private:
    bool _foo;
};

} }  // namespace Djinni::TestSuite
