// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from extended_record.djinni

#include "CsExtendedRecord.hpp"  // my header
#include "Marshal.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

ExtendedRecord::ExtendedRecord(bool foo)
: _foo(foo)
{}

bool ExtendedRecord::Foo::get()
{
    return _foo;
}

System::String^ ExtendedRecord::ToString()
{
    return "ExtendedRecord[TODO]"; // TODO
}

ExtendedRecord::CppType ExtendedRecord::ToCpp(ExtendedRecord::CsType^ cs)
{
    ASSERT(cs != nullptr);
    return {::djinni::Bool::ToCpp(cs->Foo)};
}

ExtendedRecord::CsType^ ExtendedRecord::FromCpp(const ExtendedRecord::CppType& cpp)
{
    return gcnew ExtendedRecord::CsType(::djinni::Bool::FromCpp(cpp.foo));
}

} }  // namespace Djinni::TestSuite
