// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

#pragma once

#include "CsClientInterface.hpp"
#include "CsClientReturnedRecord.hpp"
#include "extern_interface_1.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

public ref class ExternInterface1 abstract {
public:
    virtual ClientReturnedRecord^ Foo(ClientInterface^ i) abstract;

internal:
    using CppType = std::shared_ptr<::ExternInterface1>;
    using CppOptType = std::shared_ptr<::ExternInterface1>;
    using CsType = ExternInterface1^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};

} }  // namespace Djinni::TestSuite
