// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

#pragma once

#include "CsExternRecordWithDerivings.hpp"
#include "CsTestHelpers.hpp"
#include "extern_interface_2.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

public ref class ExternInterface2 abstract {
public:
    virtual ExternRecordWithDerivings^ Foo(TestHelpers^ i) abstract;

internal:
    using CppType = std::shared_ptr<::ExternInterface2>;
    using CppOptType = std::shared_ptr<::ExternInterface2>;
    using CsType = ExternInterface2^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};

} }  // namespace Djinni::TestSuite
