// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

#pragma once

#include "CsColor.hpp"
#include "CsRecordWithDerivings.hpp"
#include "extern_record_with_derivings.hpp"

namespace Djinni { namespace TestSuite {

/** This file tests YAML dumped by Djinni can be parsed back in */
public ref class ExternRecordWithDerivings : System::IComparable<ExternRecordWithDerivings^>, System::IEquatable<ExternRecordWithDerivings^> {
public:

    property RecordWithDerivings^ Member
    {
        RecordWithDerivings^ get();
    }

    property Color E
    {
        Color get();
    }

    ExternRecordWithDerivings(RecordWithDerivings^ member,
                              Color e);

    System::String^ ToString() override;

    virtual bool Equals(ExternRecordWithDerivings^ other);
    bool Equals(System::Object^ obj) override;
    int GetHashCode() override;

    virtual int CompareTo(ExternRecordWithDerivings^ other);
internal:
    using CppType = ::ExternRecordWithDerivings;
    using CsType = ExternRecordWithDerivings;

    static CppType ToCpp(CsType^ cs);
    static CsType^ FromCpp(const CppType& cpp);

private:
    RecordWithDerivings^ _member;
    Color _e;
};

} }  // namespace Djinni::TestSuite
