// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from multiple_inheritance.djinni

#pragma once

#include "first_listener.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

public ref class FirstListener abstract {
public:
    virtual void First() abstract;

internal:
    using CppType = std::shared_ptr<::testsuite::FirstListener>;
    using CppOptType = std::shared_ptr<::testsuite::FirstListener>;
    using CsType = FirstListener^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};

} }  // namespace Djinni::TestSuite
