// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from multiple_inheritance.djinni

#include "CsFirstListener.hpp"  // my header
#include "Error.hpp"
#include "Marshal.hpp"
#include "WrapperCache.hpp"

namespace Djinni { namespace TestSuite {

FirstListener::CppType FirstListener::ToCpp(FirstListener::CsType cs)
{
    if (!cs) {
        return nullptr;
    }
    DJINNI_UNIMPLEMENTED("Interface not implementable in any language.");
}

FirstListener::CsType FirstListener::FromCppOpt(const FirstListener::CppOptType& cpp)
{
    if (!cpp) {
        return nullptr;
    }
    DJINNI_UNIMPLEMENTED("Interface not implementable in any language.");
}

} }  // namespace Djinni::TestSuite
