// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from extended_record.djinni

#pragma once

#include "CsExtendedRecord.hpp"
#include "interface_using_extended_record.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

public ref class InterfaceUsingExtendedRecord abstract {
public:
    virtual ExtendedRecord^ Meth(ExtendedRecord^ er) abstract;

internal:
    using CppType = std::shared_ptr<::testsuite::InterfaceUsingExtendedRecord>;
    using CppOptType = std::shared_ptr<::testsuite::InterfaceUsingExtendedRecord>;
    using CsType = InterfaceUsingExtendedRecord^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};

} }  // namespace Djinni::TestSuite
