// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#include "CsJavaOnlyListener.hpp"  // my header
#include "Error.hpp"
#include "Marshal.hpp"
#include "WrapperCache.hpp"

namespace Djinni { namespace TestSuite {

JavaOnlyListener::CppType JavaOnlyListener::ToCpp(JavaOnlyListener::CsType cs)
{
    if (!cs) {
        return nullptr;
    }
    DJINNI_UNIMPLEMENTED("Interface not implementable in any language.");
}

JavaOnlyListener::CsType JavaOnlyListener::FromCppOpt(const JavaOnlyListener::CppOptType& cpp)
{
    if (!cpp) {
        return nullptr;
    }
    DJINNI_UNIMPLEMENTED("Interface not implementable in any language.");
}

} }  // namespace Djinni::TestSuite
