// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from date.djinni

#include "CsMapDateRecord.hpp"  // my header
#include "Marshal.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

MapDateRecord::MapDateRecord(System::Collections::Generic::Dictionary<System::String^, System::DateTime>^ datesById)
: _datesById(datesById)
{}

System::Collections::Generic::Dictionary<System::String^, System::DateTime>^ MapDateRecord::DatesById::get()
{
    return _datesById;
}

System::String^ MapDateRecord::ToString()
{
    return "MapDateRecord[TODO]"; // TODO
}

MapDateRecord::CppType MapDateRecord::ToCpp(MapDateRecord::CsType^ cs)
{
    ASSERT(cs != nullptr);
    return {::djinni::Map<::djinni::String, ::djinni::Date>::ToCpp(cs->DatesById)};
}

MapDateRecord::CsType^ MapDateRecord::FromCpp(const MapDateRecord::CppType& cpp)
{
    return gcnew MapDateRecord::CsType(::djinni::Map<::djinni::String, ::djinni::Date>::FromCpp(cpp.dates_by_id));
}

} }  // namespace Djinni::TestSuite
