// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from map.djinni

#include "CsMapListRecord.hpp"  // my header
#include "Marshal.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

MapListRecord::MapListRecord(System::Collections::Generic::List<System::Collections::Generic::Dictionary<System::String^, __int64>^>^ mapList)
: _mapList(mapList)
{}

System::Collections::Generic::List<System::Collections::Generic::Dictionary<System::String^, __int64>^>^ MapListRecord::MapList::get()
{
    return _mapList;
}

System::String^ MapListRecord::ToString()
{
    return "MapListRecord[TODO]"; // TODO
}

MapListRecord::CppType MapListRecord::ToCpp(MapListRecord::CsType^ cs)
{
    ASSERT(cs != nullptr);
    return {::djinni::List<::djinni::Map<::djinni::String, ::djinni::I64>>::ToCpp(cs->MapList)};
}

MapListRecord::CsType^ MapListRecord::FromCpp(const MapListRecord::CppType& cpp)
{
    return gcnew MapListRecord::CsType(::djinni::List<::djinni::Map<::djinni::String, ::djinni::I64>>::FromCpp(cpp.map_list));
}

} }  // namespace Djinni::TestSuite
