// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from map.djinni

#pragma once

#include "map_list_record.hpp"

namespace Djinni { namespace TestSuite {

public ref class MapListRecord {
public:

    property System::Collections::Generic::List<System::Collections::Generic::Dictionary<System::String^, __int64>^>^ MapList
    {
        System::Collections::Generic::List<System::Collections::Generic::Dictionary<System::String^, __int64>^>^ get();
    }

    MapListRecord(System::Collections::Generic::List<System::Collections::Generic::Dictionary<System::String^, __int64>^>^ mapList);

    System::String^ ToString() override;

internal:
    using CppType = ::testsuite::MapListRecord;
    using CsType = MapListRecord;

    static CppType ToCpp(CsType^ cs);
    static CsType^ FromCpp(const CppType& cpp);

private:
    System::Collections::Generic::List<System::Collections::Generic::Dictionary<System::String^, __int64>^>^ _mapList;
};

} }  // namespace Djinni::TestSuite
