// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from date.djinni

#pragma once

#include "Marshal.hpp"
#include "map_date_record.hpp"

namespace Djinni { namespace TestSuite {

public ref class MapDateRecord {
public:

    property System::Collections::Generic::Dictionary<System::String^, System::DateTime>^ DatesById
    {
        System::Collections::Generic::Dictionary<System::String^, System::DateTime>^ get();
    }

    MapDateRecord(System::Collections::Generic::Dictionary<System::String^, System::DateTime>^ datesById);

    System::String^ ToString() override;

internal:
    using CppType = ::testsuite::MapDateRecord;
    using CsType = MapDateRecord;

    static CppType ToCpp(CsType^ cs);
    static CsType^ FromCpp(const CppType& cpp);

private:
    System::Collections::Generic::Dictionary<System::String^, System::DateTime>^ _datesById;
};

} }  // namespace Djinni::TestSuite
