// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from map.djinni

#include "CsMapRecord.hpp"  // my header
#include "Marshal.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

MapRecord::MapRecord(System::Collections::Generic::Dictionary<System::String^, __int64>^ map,
                     System::Collections::Generic::Dictionary<int, int>^ imap)
: _map(map)
, _imap(imap)
{}

System::Collections::Generic::Dictionary<System::String^, __int64>^ MapRecord::Map::get()
{
    return _map;
}

System::Collections::Generic::Dictionary<int, int>^ MapRecord::Imap::get()
{
    return _imap;
}

System::String^ MapRecord::ToString()
{
    return "MapRecord[TODO]"; // TODO
}

MapRecord::CppType MapRecord::ToCpp(MapRecord::CsType^ cs)
{
    ASSERT(cs != nullptr);
    return {::djinni::Map<::djinni::String, ::djinni::I64>::ToCpp(cs->Map),
            ::djinni::Map<::djinni::I32, ::djinni::I32>::ToCpp(cs->Imap)};
}

MapRecord::CsType^ MapRecord::FromCpp(const MapRecord::CppType& cpp)
{
    return gcnew MapRecord::CsType(::djinni::Map<::djinni::String, ::djinni::I64>::FromCpp(cpp.map),
                                   ::djinni::Map<::djinni::I32, ::djinni::I32>::FromCpp(cpp.imap));
}

} }  // namespace Djinni::TestSuite
