// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nested_collection.djinni

#pragma once

#include "nested_collection.hpp"

namespace Djinni { namespace TestSuite {

public ref class NestedCollection {
public:

    property System::Collections::Generic::List<System::Collections::Generic::HashSet<System::String^>^>^ SetList
    {
        System::Collections::Generic::List<System::Collections::Generic::HashSet<System::String^>^>^ get();
    }

    NestedCollection(System::Collections::Generic::List<System::Collections::Generic::HashSet<System::String^>^>^ setList);

    System::String^ ToString() override;

internal:
    using CppType = ::testsuite::NestedCollection;
    using CsType = NestedCollection;

    static CppType ToCpp(CsType^ cs);
    static CsType^ FromCpp(const CppType& cpp);

private:
    System::Collections::Generic::List<System::Collections::Generic::HashSet<System::String^>^>^ _setList;
};

} }  // namespace Djinni::TestSuite
