// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nested_collection.djinni

#include "CsNestedCollection.hpp"  // my header
#include "Marshal.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

NestedCollection::NestedCollection(System::Collections::Generic::List<System::Collections::Generic::HashSet<System::String^>^>^ setList)
: _setList(setList)
{}

System::Collections::Generic::List<System::Collections::Generic::HashSet<System::String^>^>^ NestedCollection::SetList::get()
{
    return _setList;
}

System::String^ NestedCollection::ToString()
{
    return "NestedCollection[TODO]"; // TODO
}

NestedCollection::CppType NestedCollection::ToCpp(NestedCollection::CsType^ cs)
{
    ASSERT(cs != nullptr);
    return {::djinni::List<::djinni::Set<::djinni::String>>::ToCpp(cs->SetList)};
}

NestedCollection::CsType^ NestedCollection::FromCpp(const NestedCollection::CppType& cpp)
{
    return gcnew NestedCollection::CsType(::djinni::List<::djinni::Set<::djinni::String>>::FromCpp(cpp.set_list));
}

} }  // namespace Djinni::TestSuite
