// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#include "CsObjcOnlyListener.hpp"  // my header
#include "Error.hpp"
#include "Marshal.hpp"
#include "WrapperCache.hpp"

namespace Djinni { namespace TestSuite {

ObjcOnlyListener::CppType ObjcOnlyListener::ToCpp(ObjcOnlyListener::CsType cs)
{
    if (!cs) {
        return nullptr;
    }
    DJINNI_UNIMPLEMENTED("Interface not implementable in any language.");
}

ObjcOnlyListener::CsType ObjcOnlyListener::FromCppOpt(const ObjcOnlyListener::CppOptType& cpp)
{
    if (!cpp) {
        return nullptr;
    }
    DJINNI_UNIMPLEMENTED("Interface not implementable in any language.");
}

} }  // namespace Djinni::TestSuite
