// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from primitive_list.djinni

#pragma once

#include "primitive_list.hpp"

namespace Djinni { namespace TestSuite {

public ref class PrimitiveList {
public:

    property System::Collections::Generic::List<__int64>^ List
    {
        System::Collections::Generic::List<__int64>^ get();
    }

    PrimitiveList(System::Collections::Generic::List<__int64>^ list);

    System::String^ ToString() override;

internal:
    using CppType = ::testsuite::PrimitiveList;
    using CsType = PrimitiveList;

    static CppType ToCpp(CsType^ cs);
    static CsType^ FromCpp(const CppType& cpp);

private:
    System::Collections::Generic::List<__int64>^ _list;
};

} }  // namespace Djinni::TestSuite
