// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from duration.djinni

#pragma once

#include "Duration-cs.hpp"
#include "record_with_duration_and_derivings.hpp"

namespace Djinni { namespace TestSuite {

public ref class RecordWithDurationAndDerivings : System::IComparable<RecordWithDurationAndDerivings^>, System::IEquatable<RecordWithDurationAndDerivings^> {
public:

    property System::TimeSpan Dt
    {
        System::TimeSpan get();
    }

    RecordWithDurationAndDerivings(System::TimeSpan dt);

    System::String^ ToString() override;

    virtual bool Equals(RecordWithDurationAndDerivings^ other);
    bool Equals(System::Object^ obj) override;
    int GetHashCode() override;

    virtual int CompareTo(RecordWithDurationAndDerivings^ other);
internal:
    using CppType = ::testsuite::RecordWithDurationAndDerivings;
    using CsType = RecordWithDurationAndDerivings;

    static CppType ToCpp(CsType^ cs);
    static CsType^ FromCpp(const CppType& cpp);

private:
    System::TimeSpan _dt;
};

} }  // namespace Djinni::TestSuite
