// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

#include "CsRecordWithFlags.hpp"  // my header
#include "Marshal.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

RecordWithFlags::RecordWithFlags(AccessFlags access)
: _access(access)
{}

AccessFlags RecordWithFlags::Access::get()
{
    return _access;
}

System::String^ RecordWithFlags::ToString()
{
    return "RecordWithFlags[TODO]"; // TODO
}

RecordWithFlags::CppType RecordWithFlags::ToCpp(RecordWithFlags::CsType^ cs)
{
    ASSERT(cs != nullptr);
    return {::djinni::Enum<::testsuite::access_flags, AccessFlags>::ToCpp(cs->Access)};
}

RecordWithFlags::CsType^ RecordWithFlags::FromCpp(const RecordWithFlags::CppType& cpp)
{
    return gcnew RecordWithFlags::CsType(::djinni::Enum<::testsuite::access_flags, AccessFlags>::FromCpp(cpp.access));
}

} }  // namespace Djinni::TestSuite
