// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from multiple_inheritance.djinni

#pragma once

#include "return_one.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

public ref class ReturnOne abstract {
public:
    static ReturnOne^ GetInstance();

    virtual char DoReturnOne() abstract;

internal:
    using CppType = std::shared_ptr<::testsuite::ReturnOne>;
    using CppOptType = std::shared_ptr<::testsuite::ReturnOne>;
    using CsType = ReturnOne^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};

} }  // namespace Djinni::TestSuite
