// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from extended_record.djinni

#pragma once

#include "CsExtendedRecord.hpp"
#include "record_using_extended_record.hpp"

namespace Djinni { namespace TestSuite {

public ref class RecordUsingExtendedRecord {
public:

    static initonly RecordUsingExtendedRecord^ Cr;

    static RecordUsingExtendedRecord() {
        Cr = gcnew RecordUsingExtendedRecord(
            gcnew ExtendedRecord(
                false /* _foo */ ) /* _er */ );
    }

    property ExtendedRecord^ Er
    {
        ExtendedRecord^ get();
    }

    RecordUsingExtendedRecord(ExtendedRecord^ er);

    System::String^ ToString() override;

internal:
    using CppType = ::testsuite::RecordUsingExtendedRecord;
    using CsType = RecordUsingExtendedRecord;

    static CppType ToCpp(CsType^ cs);
    static CsType^ FromCpp(const CppType& cpp);

private:
    ExtendedRecord^ _er;
};

} }  // namespace Djinni::TestSuite
