// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from multiple_inheritance.djinni

#include "CsReturnOne.hpp"  // my header
#include "Error.hpp"
#include "Marshal.hpp"
#include "WrapperCache.hpp"

namespace Djinni { namespace TestSuite {

ReturnOne^ ReturnOne::GetInstance() {
    try {
        auto cs_result = ::testsuite::ReturnOne::get_instance();
        return ::Djinni::TestSuite::ReturnOne::FromCpp(cs_result);
    } DJINNI_TRANSLATE_EXCEPTIONS()
    return nullptr; // Unreachable! (Silencing compiler warnings.)
}

ref class ReturnOneCppProxy : public ReturnOne {
    using CppType = std::shared_ptr<::testsuite::ReturnOne>;
    using HandleType = ::djinni::CppProxyCache::Handle<CppType>;
public:
    ReturnOneCppProxy(const CppType& cppRef) : _cppRefHandle(new HandleType(cppRef)) {}

    char DoReturnOne() override {
        try {
            auto cs_result = _cppRefHandle->get()->return_one();
            return ::djinni::I8::FromCpp(cs_result);
        } DJINNI_TRANSLATE_EXCEPTIONS()
        return 0; // Unreachable! (Silencing compiler warnings.)
    }

    CppType djinni_private_get_proxied_cpp_object() {
        return _cppRefHandle->get();
    }

private:
    AutoPtr<HandleType> _cppRefHandle;
};

ReturnOne::CppType ReturnOne::ToCpp(ReturnOne::CsType cs)
{
    if (!cs) {
        return nullptr;
    }
    return dynamic_cast<ReturnOneCppProxy^>(cs)->djinni_private_get_proxied_cpp_object();
}

ReturnOne::CsType ReturnOne::FromCppOpt(const ReturnOne::CppOptType& cpp)
{
    if (!cpp) {
        return nullptr;
    }
    return ::djinni::get_cpp_proxy<ReturnOneCppProxy^>(cpp);
}

} }  // namespace Djinni::TestSuite
