// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from derivings.djinni

#pragma once

#include "CsRecordWithDerivings.hpp"
#include "record_with_nested_derivings.hpp"

namespace Djinni { namespace TestSuite {

public ref class RecordWithNestedDerivings : System::IComparable<RecordWithNestedDerivings^>, System::IEquatable<RecordWithNestedDerivings^> {
public:

    property int Key
    {
        int get();
    }

    property RecordWithDerivings^ Rec
    {
        RecordWithDerivings^ get();
    }

    RecordWithNestedDerivings(int key,
                              RecordWithDerivings^ rec);

    System::String^ ToString() override;

    virtual bool Equals(RecordWithNestedDerivings^ other);
    bool Equals(System::Object^ obj) override;
    int GetHashCode() override;

    virtual int CompareTo(RecordWithNestedDerivings^ other);
internal:
    using CppType = ::testsuite::RecordWithNestedDerivings;
    using CsType = RecordWithNestedDerivings;

    static CppType ToCpp(CsType^ cs);
    static CsType^ FromCpp(const CppType& cpp);

private:
    int _key;
    RecordWithDerivings^ _rec;
};

} }  // namespace Djinni::TestSuite
