// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

#pragma once

#include "CsAccessFlags.hpp"
#include "record_with_flags.hpp"

namespace Djinni { namespace TestSuite {

public ref class RecordWithFlags {
public:

    property AccessFlags Access
    {
        AccessFlags get();
    }

    RecordWithFlags(AccessFlags access);

    System::String^ ToString() override;

internal:
    using CppType = ::testsuite::RecordWithFlags;
    using CsType = RecordWithFlags;

    static CppType ToCpp(CsType^ cs);
    static CsType^ FromCpp(const CppType& cpp);

private:
    AccessFlags _access;
};

} }  // namespace Djinni::TestSuite
