// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#pragma once

#include "reverse_client_interface.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

public ref class ReverseClientInterface abstract {
public:
    virtual System::String^ ReturnStr() abstract;

    virtual System::String^ MethTakingInterface(ReverseClientInterface^ i) abstract;

    virtual System::String^ MethTakingOptionalInterface(ReverseClientInterface^ i) abstract;

    static ReverseClientInterface^ Create();

internal:
    using CppType = std::shared_ptr<::testsuite::ReverseClientInterface>;
    using CppOptType = std::shared_ptr<::testsuite::ReverseClientInterface>;
    using CsType = ReverseClientInterface^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};

} }  // namespace Djinni::TestSuite
