// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from multiple_inheritance.djinni

#pragma once

#include "return_two.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

public ref class ReturnTwo abstract {
public:
    static ReturnTwo^ GetInstance();

    virtual char DoReturnTwo() abstract;

internal:
    using CppType = std::shared_ptr<::testsuite::ReturnTwo>;
    using CppOptType = std::shared_ptr<::testsuite::ReturnTwo>;
    using CsType = ReturnTwo^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};

} }  // namespace Djinni::TestSuite
