// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from extended_record.djinni

#include "CsRecordUsingExtendedRecord.hpp"  // my header
#include "Marshal.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

RecordUsingExtendedRecord::RecordUsingExtendedRecord(ExtendedRecord^ er)
: _er(er)
{}

ExtendedRecord^ RecordUsingExtendedRecord::Er::get()
{
    return _er;
}

System::String^ RecordUsingExtendedRecord::ToString()
{
    return "RecordUsingExtendedRecord[TODO]"; // TODO
}

RecordUsingExtendedRecord::CppType RecordUsingExtendedRecord::ToCpp(RecordUsingExtendedRecord::CsType^ cs)
{
    ASSERT(cs != nullptr);
    return {::Djinni::TestSuite::ExtendedRecord::ToCpp(cs->Er)};
}

RecordUsingExtendedRecord::CsType^ RecordUsingExtendedRecord::FromCpp(const RecordUsingExtendedRecord::CppType& cpp)
{
    return gcnew RecordUsingExtendedRecord::CsType(::Djinni::TestSuite::ExtendedRecord::FromCpp(cpp.er));
}

} }  // namespace Djinni::TestSuite
