// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from set.djinni

#include "CsSetRecord.hpp"  // my header
#include "Marshal.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

SetRecord::SetRecord(System::Collections::Generic::HashSet<System::String^>^ set,
                     System::Collections::Generic::HashSet<int>^ iset)
: _set(set)
, _iset(iset)
{}

System::Collections::Generic::HashSet<System::String^>^ SetRecord::Set::get()
{
    return _set;
}

System::Collections::Generic::HashSet<int>^ SetRecord::Iset::get()
{
    return _iset;
}

System::String^ SetRecord::ToString()
{
    return "SetRecord[TODO]"; // TODO
}

SetRecord::CppType SetRecord::ToCpp(SetRecord::CsType^ cs)
{
    ASSERT(cs != nullptr);
    return {::djinni::Set<::djinni::String>::ToCpp(cs->Set),
            ::djinni::Set<::djinni::I32>::ToCpp(cs->Iset)};
}

SetRecord::CsType^ SetRecord::FromCpp(const SetRecord::CppType& cpp)
{
    return gcnew SetRecord::CsType(::djinni::Set<::djinni::String>::FromCpp(cpp.set),
                                   ::djinni::Set<::djinni::I32>::FromCpp(cpp.iset));
}

} }  // namespace Djinni::TestSuite
