// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from multiple_inheritance.djinni

#include "CsSecondListener.hpp"  // my header
#include "Error.hpp"
#include "Marshal.hpp"
#include "WrapperCache.hpp"

namespace Djinni { namespace TestSuite {

SecondListener::CppType SecondListener::ToCpp(SecondListener::CsType cs)
{
    if (!cs) {
        return nullptr;
    }
    DJINNI_UNIMPLEMENTED("Interface not implementable in any language.");
}

SecondListener::CsType SecondListener::FromCppOpt(const SecondListener::CppOptType& cpp)
{
    if (!cpp) {
        return nullptr;
    }
    DJINNI_UNIMPLEMENTED("Interface not implementable in any language.");
}

} }  // namespace Djinni::TestSuite
