// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from multiple_inheritance.djinni

#pragma once

#include "second_listener.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

public ref class SecondListener abstract {
public:
    virtual void Second() abstract;

internal:
    using CppType = std::shared_ptr<::testsuite::SecondListener>;
    using CppOptType = std::shared_ptr<::testsuite::SecondListener>;
    using CsType = SecondListener^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};

} }  // namespace Djinni::TestSuite
