// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from set.djinni

#pragma once

#include "set_record.hpp"

namespace Djinni { namespace TestSuite {

public ref class SetRecord {
public:

    property System::Collections::Generic::HashSet<System::String^>^ Set
    {
        System::Collections::Generic::HashSet<System::String^>^ get();
    }

    property System::Collections::Generic::HashSet<int>^ Iset
    {
        System::Collections::Generic::HashSet<int>^ get();
    }

    SetRecord(System::Collections::Generic::HashSet<System::String^>^ set,
              System::Collections::Generic::HashSet<int>^ iset);

    System::String^ ToString() override;

internal:
    using CppType = ::testsuite::SetRecord;
    using CsType = SetRecord;

    static CppType ToCpp(CsType^ cs);
    static CsType^ FromCpp(const CppType& cpp);

private:
    System::Collections::Generic::HashSet<System::String^>^ _set;
    System::Collections::Generic::HashSet<int>^ _iset;
};

} }  // namespace Djinni::TestSuite
