// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user_token.djinni

#pragma once

#include "user_token.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

public ref class UserToken abstract {
public:
    virtual System::String^ Whoami() abstract;

internal:
    using CppType = std::shared_ptr<::testsuite::UserToken>;
    using CppOptType = std::shared_ptr<::testsuite::UserToken>;
    using CsType = UserToken^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};

} }  // namespace Djinni::TestSuite
