// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from varnames.djinni

#include "CsVarnameRecord.hpp"  // my header
#include "Marshal.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

VarnameRecord::VarnameRecord(char Field)
: _Field(Field)
{}

char VarnameRecord::Field::get()
{
    return _Field;
}

System::String^ VarnameRecord::ToString()
{
    return "VarnameRecord[TODO]"; // TODO
}

VarnameRecord::CppType VarnameRecord::ToCpp(VarnameRecord::CsType^ cs)
{
    ASSERT(cs != nullptr);
    return {::djinni::I8::ToCpp(cs->Field)};
}

VarnameRecord::CsType^ VarnameRecord::FromCpp(const VarnameRecord::CppType& cpp)
{
    return gcnew VarnameRecord::CsType(::djinni::I8::FromCpp(cpp._field_));
}

} }  // namespace Djinni::TestSuite
