// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from varnames.djinni

#pragma once

#include "CsVarnameRecord.hpp"
#include "_varname_interface_.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

public ref class VarnameInterface abstract {
public:
    virtual VarnameRecord^ Rmethod(VarnameRecord^ RArg) abstract;

    virtual VarnameInterface^ Imethod(VarnameInterface^ IArg) abstract;

internal:
    using CppType = std::shared_ptr<::testsuite::VarnameInterface>;
    using CppOptType = std::shared_ptr<::testsuite::VarnameInterface>;
    using CsType = VarnameInterface^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};

} }  // namespace Djinni::TestSuite
