// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from varnames.djinni

#pragma once

#include "_varname_record_.hpp"

namespace Djinni { namespace TestSuite {

/**
 * Underscore is used as a separator in Djinni names, so we don't really
 * anticipate it to be used as a prefix/suffix.  Some name styles behave
 * badly when it is.  However this test case ensures we at least don't crash.
 */
public ref class VarnameRecord {
public:

    property char Field
    {
        char get();
    }

    VarnameRecord(char Field);

    System::String^ ToString() override;

internal:
    using CppType = ::testsuite::VarnameRecord;
    using CsType = VarnameRecord;

    static CppType ToCpp(CsType^ cs);
    static CsType^ FromCpp(const CppType& cpp);

private:
    char _Field;
};

} }  // namespace Djinni::TestSuite
