// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wchar_test.djinni

#pragma once

#include "CsWcharTestRec.hpp"
#include "wchar_test_helpers.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

public ref class WcharTestHelpers abstract {
public:
    static WcharTestRec^ GetRecord();

    static System::String^ GetString();

    static bool CheckString(System::String^ str);

    static bool CheckRecord(WcharTestRec^ rec);

internal:
    using CppType = std::shared_ptr<::testsuite::WcharTestHelpers>;
    using CppOptType = std::shared_ptr<::testsuite::WcharTestHelpers>;
    using CsType = WcharTestHelpers^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};

} }  // namespace Djinni::TestSuite
