// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wchar_test.djinni

#include "CsWcharTestHelpers.hpp"  // my header
#include "Error.hpp"
#include "Marshal.hpp"
#include "WrapperCache.hpp"
#include "wchar_test_rec.hpp"

namespace Djinni { namespace TestSuite {

WcharTestRec^ WcharTestHelpers::GetRecord() {
    try {
        auto cs_result = ::testsuite::WcharTestHelpers::get_record();
        return ::Djinni::TestSuite::WcharTestRec::FromCpp(cs_result);
    } DJINNI_TRANSLATE_EXCEPTIONS()
    return nullptr; // Unreachable! (Silencing compiler warnings.)
}

System::String^ WcharTestHelpers::GetString() {
    try {
        auto cs_result = ::testsuite::WcharTestHelpers::get_string();
        return ::djinni::WString::FromCpp(cs_result);
    } DJINNI_TRANSLATE_EXCEPTIONS()
    return nullptr; // Unreachable! (Silencing compiler warnings.)
}

bool WcharTestHelpers::CheckString(System::String^ str) {
    try {
        auto cs_result = ::testsuite::WcharTestHelpers::check_string(::djinni::WString::ToCpp(str));
        return ::djinni::Bool::FromCpp(cs_result);
    } DJINNI_TRANSLATE_EXCEPTIONS()
    return 0; // Unreachable! (Silencing compiler warnings.)
}

bool WcharTestHelpers::CheckRecord(WcharTestRec^ rec) {
    try {
        auto cs_result = ::testsuite::WcharTestHelpers::check_record(::Djinni::TestSuite::WcharTestRec::ToCpp(rec));
        return ::djinni::Bool::FromCpp(cs_result);
    } DJINNI_TRANSLATE_EXCEPTIONS()
    return 0; // Unreachable! (Silencing compiler warnings.)
}

ref class WcharTestHelpersCppProxy : public WcharTestHelpers {
    using CppType = std::shared_ptr<::testsuite::WcharTestHelpers>;
    using HandleType = ::djinni::CppProxyCache::Handle<CppType>;
public:
    WcharTestHelpersCppProxy(const CppType& cppRef) : _cppRefHandle(new HandleType(cppRef)) {}

    CppType djinni_private_get_proxied_cpp_object() {
        return _cppRefHandle->get();
    }

private:
    AutoPtr<HandleType> _cppRefHandle;
};

WcharTestHelpers::CppType WcharTestHelpers::ToCpp(WcharTestHelpers::CsType cs)
{
    if (!cs) {
        return nullptr;
    }
    return dynamic_cast<WcharTestHelpersCppProxy^>(cs)->djinni_private_get_proxied_cpp_object();
}

WcharTestHelpers::CsType WcharTestHelpers::FromCppOpt(const WcharTestHelpers::CppOptType& cpp)
{
    if (!cpp) {
        return nullptr;
    }
    return ::djinni::get_cpp_proxy<WcharTestHelpersCppProxy^>(cpp);
}

} }  // namespace Djinni::TestSuite
