// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wchar_test.djinni

#include "CsWcharTestRec.hpp"  // my header
#include "Marshal.hpp"
#include <memory>

namespace Djinni { namespace TestSuite {

WcharTestRec::WcharTestRec(System::String^ s)
: _s(s)
{}

System::String^ WcharTestRec::S::get()
{
    return _s;
}

System::String^ WcharTestRec::ToString()
{
    return "WcharTestRec[TODO]"; // TODO
}

WcharTestRec::CppType WcharTestRec::ToCpp(WcharTestRec::CsType^ cs)
{
    ASSERT(cs != nullptr);
    return {::djinni::WString::ToCpp(cs->S)};
}

WcharTestRec::CsType^ WcharTestRec::FromCpp(const WcharTestRec::CppType& cpp)
{
    return gcnew WcharTestRec::CsType(::djinni::WString::FromCpp(cpp.s));
}

} }  // namespace Djinni::TestSuite
