// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wchar_test.djinni

#pragma once

#include "wchar_test_rec.hpp"

namespace Djinni { namespace TestSuite {

public ref class WcharTestRec {
public:

    property System::String^ S
    {
        System::String^ get();
    }

    WcharTestRec(System::String^ s);

    System::String^ ToString() override;

internal:
    using CppType = ::testsuite::WcharTestRec;
    using CsType = WcharTestRec;

    static CppType ToCpp(CsType^ cs);
    static CsType^ FromCpp(const CppType& cpp);

private:
    System::String^ _s;
};

} }  // namespace Djinni::TestSuite
