// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#pragma once

namespace testsuite {

class CsOnlyListener {
public:
    virtual ~CsOnlyListener() {}
};

}  // namespace testsuite
