// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#include "cs_only_listener.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBCsOnlyListener;

namespace djinni_generated {

class CsOnlyListener
{
public:
    using CppType = std::shared_ptr<::testsuite::CsOnlyListener>;
    using CppOptType = std::shared_ptr<::testsuite::CsOnlyListener>;
    using ObjcType = DBCsOnlyListener*;

    using Boxed = CsOnlyListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

