// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#import "DBCsOnlyListener+Private.h"
#import "DBCsOnlyListener.h"
#import "DJIError.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

auto CsOnlyListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    DJINNI_UNIMPLEMENTED(@"Interface not implementable in any language.");
}

auto CsOnlyListener::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    DJINNI_UNIMPLEMENTED(@"Interface not implementable in any language.");
}

}  // namespace djinni_generated
